### ISSUE TITLE
It looks like you're using the browser version of the SDK in a node.js environment. You should require('parse/node') instead.

### ISSUE THREAD

**Issue by grimaldodev** [cierrateam/nuxt-parse#5]
Im using the same exampla that you have in the readme file, but login the error:

`It looks like you're using the browser version of the SDK in a node.js environment. You should require('parse/node') instead.`

If I change to `parse/node` I get the error:

```
ERROR  Failed to compile with 2 errors 
These dependencies were not found:
* child_process in ./node_modules/xmlhttprequest/lib/XMLHttpRequest.js 
* fs in ./node_modules/xmlhttprequest/lib/XMLHttpRequest.js 
To install them, you can run: npm install --save child_process fs
```

After install the dependencies the error still happening, It can not be other module, plugin or library because If I replace `parse/node` for `parse` I get the first error again.

This is installed in a fresh new nuxt app, this is the only file created `middleware/auth.js` do you have any solution?

**Comment by vittorioe** [comment]
Thank you for submitting the issue, we’ll take a look 👀

**Comment by vittorioe** [comment]
Ah. Please take care of your version in nuxt. Please just use it in the client side. not in server side. no-ssr :)

**Comment by gp4pgit** [comment]
Or use `const Parse = require('parse/node');` instead of `const Parse = require('parse');`
Compare it to the documentation (https://docs.parseplatform.org/js/guide/)
_For server-side applications or Node.js command line tools, include 'parse/node':_
